export const demoNotifcation = [
    { name: "Ahmad", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "2 hours" },
    { name: "Ahmad", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "4 hours" },
    { name: "Ali", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "10 hours" },
    { name: "Muzamil", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "14 hours" },
    { name: "Bilal", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "2 days" },
    { name: "Shaheeer", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "7 days" },
    { name: "Adil", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "8 days" },
    { name: "Waleed", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "14 days" },
    { name: "Anas", detail: "Use simple and straightforward language that is easy for your audience to understand. Avoid jargon, abbreviations, or slang that could potentially confuse your reader.", time: "15 days" }
]
export const Racer = [{ value: "white", label: "White" }, { value: "black_Or_African_American", label: "Black or African American" }, { value: "american_Indian_Or_Alaska_Native", label: "American Indian or Alaska Native" }, { value: "asian", label: "Asian" }, { value: "native_Hawaiian_Or_Other_Pacific_Islander", label: "Native Hawaiian or Other Pacific Islander" }]
export const veteranStatusOptions = [
    { value: "not_a_protected_veteran", label: "Not a Protected Veteran" },
    { value: "disabled_veteran", label: "Disabled Veteran" },
    { value: "recently_separated_veteran", label: "Recently Separated Veteran" },
    { value: "active_duty_wartime_or_campaign_badge_veteran", label: "Active Duty Wartime or Campaign Badge Veteran" },
    { value: "armed_forces_service_medal_veteran", label: "Armed Forces Service Medal Veteran" },
    { value: "not_a_veteran", label: "Not a Veteran" }
  ];
 export const veteranStatusOptionEnum = {
    not_a_protected_veteran: "Not a Protected Veteran",
    disabled_veteran: "Disabled Veteran",
    recently_separated_veteran: "Recently Separated Veteran",
    active_duty_wartime_or_campaign_badge_veteran: "Active Duty Wartime or Campaign Badge Veteran",
    armed_forces_service_medal_veteran: "Armed Forces Service Medal Veteran",
    not_a_veteran: "Not a Veteran"
  };
  
  
export const demoDataAppliedAppllicnt = [{
    __ID: "1",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: [{
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },],
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Answer",
        "good_fit_reason": "Answer",
        "experience_qualifications": "Answer",
        "career_goals": "Answer",
    }
},
{
    __ID: "2",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "3",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "4",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "5",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "6",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "7",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
},
{
    __ID: "8",
    name: "Sale Manager",
    adress: "USA Citizen",
    country: "USA",
    educatioin: "Master",
    experienceLevel: "Entry Level",
    rating: 75,
    createdAt: "2024-07-29T14:48:22.701Z",
    profile: {
        gender: "Male",
        motherLnaguage: "English",
        otherLanguage: "Urde",
        citizenStatus: "U.S citizen",
        ableToWorkUs: "yes",
        veteranStatus: "No",
        race: "Black",
        hispanic: "No",
        elegation: "No",
        enonimusField: "No",
    },
    work: {
        jobType: "Web Developer",
        employer: "Ahmad",
        experience: "Entry Level",
        city: "Paris",
        country: "USA",
        from: "2022",
        to: "",
        onGoing: true,
    },
    educatioin1: [{
        acedemicCenter: "MIT",
        field: "B.S Computer Science",
        from: "2022",
        to: "",
        onGoing: true,
        digree: "Bachelor",
        gpa: 3.5
    }],
    skills: ["C++", "C#", "Java Script", "Git Hub", "HTML", "Css", "Tailwind", "SQL"],
    portfolio: {},
    answer: {
        "interest_in_position": "Why are you interested in this position?",
        "good_fit_reason": "What makes you a good fit for this role?",
        "experience_qualifications": "Describe your relevant experience and qualifications.",
        "career_goals": "What are your career goals and how does this position align with them?",
    }
}
]

